// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfcCEhVcQwPa075wRu3eA3j9xW8GGUIuY',
    appId: '1:111192289134:web:c7b26158c5c407cdaf9b7f',
    messagingSenderId: '111192289134',
    projectId: 'authtutorial-24cb1',
    authDomain: 'authtutorial-24cb1.firebaseapp.com',
    storageBucket: 'authtutorial-24cb1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMkN9gEIsvyofFLAE8gZhHw_V66Nk7cBs',
    appId: '1:111192289134:android:8663c98e562454ddaf9b7f',
    messagingSenderId: '111192289134',
    projectId: 'authtutorial-24cb1',
    storageBucket: 'authtutorial-24cb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9LL9T2vRIDtKcocBGWUvRnUfn3kQMYYw',
    appId: '1:111192289134:ios:26fba6acc34bffe0af9b7f',
    messagingSenderId: '111192289134',
    projectId: 'authtutorial-24cb1',
    storageBucket: 'authtutorial-24cb1.appspot.com',
    iosClientId: '111192289134-it0r2mc9970otgcl9lova6q0tlkkv2ve.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9LL9T2vRIDtKcocBGWUvRnUfn3kQMYYw',
    appId: '1:111192289134:ios:26fba6acc34bffe0af9b7f',
    messagingSenderId: '111192289134',
    projectId: 'authtutorial-24cb1',
    storageBucket: 'authtutorial-24cb1.appspot.com',
    iosClientId: '111192289134-it0r2mc9970otgcl9lova6q0tlkkv2ve.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );
}
